import XCTest
@testable import HoehnPhotosOrganizer

// MARK: - Test Helpers

/// Replicates the CurveBuilderView interpolation algorithm (private in production).
/// Linear interpolation over sorted CurveStep array for a given t in [0,1].
private func interpolate(t: Double, steps: [CurveStep]) -> Double {
    guard !steps.isEmpty else { return t }
    if t <= steps.first!.input { return steps.first!.output }
    if t >= steps.last!.input  { return steps.last!.output  }

    for i in 0..<(steps.count - 1) {
        let lo = steps[i]
        let hi = steps[i + 1]
        if t >= lo.input && t <= hi.input {
            let span = hi.input - lo.input
            guard span > 0 else { return lo.output }
            let fraction = (t - lo.input) / span
            return lo.output + fraction * (hi.output - lo.output)
        }
    }
    return steps.last!.output
}

/// Apply gamma curve: pow(value, gamma), clamped to [0, 1].
private func applyGamma(_ value: Double, gamma: Double) -> Double {
    guard value >= 0 else { return 0 }
    guard value <= 1 else { return 1 }
    return pow(value, gamma)
}

/// Blend two UInt16 arrays (256 entries each) using zone weights.
/// weights is a SplitToneConfig-style struct with highlights/midtones/shadows (0-100).
/// Shadows = input indices 0-84, Midtones = 85-169, Highlights = 170-255.
/// weight values represent how much of curve1 to use (100 = all curve1, 0 = all curve2).
private func blendCurves(
    curve1: [UInt16],
    curve2: [UInt16],
    shadowWeight: Double,
    midtoneWeight: Double,
    highlightWeight: Double
) -> [UInt16] {
    precondition(curve1.count == 256 && curve2.count == 256)
    var result = [UInt16](repeating: 0, count: 256)
    for i in 0..<256 {
        let weight: Double
        if i < 85 {
            weight = shadowWeight / 100.0
        } else if i < 170 {
            weight = midtoneWeight / 100.0
        } else {
            weight = highlightWeight / 100.0
        }
        let blended = Double(curve1[i]) * weight + Double(curve2[i]) * (1.0 - weight)
        result[i] = UInt16(min(max(blended + 0.5, 0), 65535))
    }
    return result
}

/// Replicate the CurveBuilderView export logic: CurveStep array -> QTR .txt string.
private func exportCurveTxt(steps: [CurveStep]) -> String {
    var lines: [String] = []
    lines.append("# QTR Linearization Curve")
    lines.append("# Generated by HoehnPhotos CurveLab")
    lines.append("# Values: 256 ink density steps (0 = no ink, 255 = full ink)")
    lines.append("")

    if steps.isEmpty {
        for i in 0..<256 {
            lines.append("\(i)")
        }
    } else {
        let sorted = steps.sorted(by: { $0.input < $1.input })
        for i in 0..<256 {
            let t = Double(i) / 255.0
            let output = interpolate(t: t, steps: sorted)
            let value = Int(output * 255.0 + 0.5)
            lines.append("\(min(max(value, 0), 255))")
        }
    }

    return lines.joined(separator: "\n")
}

// MARK: - Fixtures

/// Fixtures for CurveMath tests, matching the CurveLabFixtures API.
private enum CurveLabFixtures {

    /// Evenly spaced linear steps from (0,0) to (1,1).
    static func testLinearCurveSteps(count: Int) -> [CurveStep] {
        guard count > 1 else {
            return count == 1 ? [CurveStep(input: 0.5, output: 0.5)] : []
        }
        return (0..<count).map { i in
            let t = Double(i) / Double(count - 1)
            return CurveStep(input: t, output: t)
        }
    }

    /// S-curve steps: compressed shadows/highlights, steeper midtones.
    /// Uses a sigmoid-like remapping: output = 0.5 + 0.5 * tanh(3 * (input - 0.5))
    /// normalized to 0-1.
    static func testSCurveCurveSteps(count: Int) -> [CurveStep] {
        guard count > 1 else {
            return count == 1 ? [CurveStep(input: 0.5, output: 0.5)] : []
        }
        return (0..<count).map { i in
            let input = Double(i) / Double(count - 1)
            // Sigmoid S-curve centered at 0.5
            let raw = 1.0 / (1.0 + exp(-6.0 * (input - 0.5)))
            // Normalize so endpoints are exactly 0 and 1
            let rawMin = 1.0 / (1.0 + exp(-6.0 * (0.0 - 0.5)))
            let rawMax = 1.0 / (1.0 + exp(-6.0 * (1.0 - 0.5)))
            let output = (raw - rawMin) / (rawMax - rawMin)
            return CurveStep(input: input, output: output)
        }
    }

    /// Linear ramp ink channel: values go from 0 to maxValue across 256 entries.
    static func testInkChannelLinear(name: String = "K", maxValue: UInt16 = 65535) -> InkChannel {
        let values = (0..<256).map { i in
            UInt16(Double(i) / 255.0 * Double(maxValue) + 0.5)
        }
        return InkChannel(name: name, values: values)
    }

    /// Empty ink channel: all 256 values are zero.
    static func testInkChannelEmpty(name: String = "Empty") -> InkChannel {
        InkChannel(name: name, values: [UInt16](repeating: 0, count: 256))
    }

    /// Bell curve ink channel: peaks at a given index, tapers by Gaussian width.
    static func testInkChannelBellCurve(name: String = "LK", peak: Int = 128, width: Double = 40.0) -> InkChannel {
        let values = (0..<256).map { i in
            let dist = Double(i - peak)
            let gauss = exp(-(dist * dist) / (2.0 * width * width))
            return UInt16(gauss * 65535.0 + 0.5)
        }
        return InkChannel(name: name, values: values)
    }
}

// MARK: - CurveMathTests

final class CurveMathTests: XCTestCase {

    // ================================================================
    // MARK: - Linear Interpolation Tests
    // ================================================================

    /// 2 steps (0,0)->(1,1), interpolate at t=0.5 -> output 0.5
    func test_interpolate_linearSteps_midpoint() {
        let steps = [
            CurveStep(input: 0, output: 0),
            CurveStep(input: 1, output: 1)
        ]
        let result = interpolate(t: 0.5, steps: steps)
        XCTAssertEqual(result, 0.5, accuracy: 1e-10)
    }

    /// t=0 -> output=0, t=1 -> output=1
    func test_interpolate_linearSteps_atEndpoints() {
        let steps = [
            CurveStep(input: 0, output: 0),
            CurveStep(input: 1, output: 1)
        ]
        XCTAssertEqual(interpolate(t: 0, steps: steps), 0.0, accuracy: 1e-10)
        XCTAssertEqual(interpolate(t: 1, steps: steps), 1.0, accuracy: 1e-10)
    }

    /// S-curve steps, t=0.5 -> output != 0.5 (compressed midtones shift the midpoint)
    func test_interpolate_sCurve_midpointNotHalf() {
        let steps = CurveLabFixtures.testSCurveCurveSteps(count: 21)
        let result = interpolate(t: 0.5, steps: steps)
        // S-curve is symmetric around 0.5 for a centered sigmoid, so the
        // midpoint output will be ~0.5 but the key property is that nearby
        // values are steeper. Verify the curve is non-linear by checking
        // that t=0.25 output differs significantly from 0.25.
        let quarterResult = interpolate(t: 0.25, steps: steps)
        XCTAssertNotEqual(quarterResult, 0.25, accuracy: 0.02,
                          "S-curve at t=0.25 should differ from linear 0.25")
    }

    /// t=-0.1 -> returns first step's output (clamp below range)
    func test_interpolate_belowRange_clampsToFirst() {
        let steps = [
            CurveStep(input: 0.0, output: 0.2),
            CurveStep(input: 1.0, output: 0.8)
        ]
        let result = interpolate(t: -0.1, steps: steps)
        XCTAssertEqual(result, 0.2, accuracy: 1e-10,
                       "Below-range t should clamp to first step output")
    }

    /// t=1.1 -> returns last step's output (clamp above range)
    func test_interpolate_aboveRange_clampsToLast() {
        let steps = [
            CurveStep(input: 0.0, output: 0.2),
            CurveStep(input: 1.0, output: 0.8)
        ]
        let result = interpolate(t: 1.1, steps: steps)
        XCTAssertEqual(result, 0.8, accuracy: 1e-10,
                       "Above-range t should clamp to last step output")
    }

    /// Empty array -> returns t itself (identity fallback)
    func test_interpolate_emptySteps_returnsIdentity() {
        let result = interpolate(t: 0.73, steps: [])
        XCTAssertEqual(result, 0.73, accuracy: 1e-10,
                       "Empty steps should return t as identity")
    }

    /// Single step -> always returns that step's output
    func test_interpolate_singleStep_returnsStepOutput() {
        let steps = [CurveStep(input: 0.5, output: 0.7)]
        // Any t <= 0.5 returns first (only) output; any t >= 0.5 also returns it
        XCTAssertEqual(interpolate(t: 0.0, steps: steps), 0.7, accuracy: 1e-10)
        XCTAssertEqual(interpolate(t: 0.5, steps: steps), 0.7, accuracy: 1e-10)
        XCTAssertEqual(interpolate(t: 1.0, steps: steps), 0.7, accuracy: 1e-10)
    }

    /// 256 linear steps, interpolating at each -> matches input within epsilon
    func test_interpolate_256StepsLinear_matchesIdentity() {
        let steps = CurveLabFixtures.testLinearCurveSteps(count: 256)
        for i in 0..<256 {
            let t = Double(i) / 255.0
            let result = interpolate(t: t, steps: steps)
            XCTAssertEqual(result, t, accuracy: 1e-9,
                           "Linear 256-step curve at index \(i) should be identity")
        }
    }

    // ================================================================
    // MARK: - Curve Step Generation
    // ================================================================

    /// 21 steps from 0 to 1, verify spacing ~ 0.05
    func test_linearCurveSteps_21_evenlySpaced() {
        let steps = CurveLabFixtures.testLinearCurveSteps(count: 21)
        XCTAssertEqual(steps.count, 21)
        let expectedSpacing = 1.0 / 20.0  // 0.05
        for i in 1..<steps.count {
            let spacing = steps[i].input - steps[i - 1].input
            XCTAssertEqual(spacing, expectedSpacing, accuracy: 1e-10,
                           "Step \(i) spacing should be ~0.05")
        }
    }

    /// 256 linear steps: first input=0, last input=1
    func test_linearCurveSteps_256_coversFullRange() {
        let steps = CurveLabFixtures.testLinearCurveSteps(count: 256)
        XCTAssertEqual(steps.count, 256)
        XCTAssertEqual(steps.first!.input, 0.0, accuracy: 1e-10)
        XCTAssertEqual(steps.last!.input, 1.0, accuracy: 1e-10)
        XCTAssertEqual(steps.first!.output, 0.0, accuracy: 1e-10)
        XCTAssertEqual(steps.last!.output, 1.0, accuracy: 1e-10)
    }

    /// S-curve middle steps have steeper slope than endpoint steps
    func test_sCurveSteps_hasInflectionPoint() {
        let steps = CurveLabFixtures.testSCurveCurveSteps(count: 21)
        // Slope near endpoints (steps 0-1 and 19-20)
        let slopeStart = (steps[1].output - steps[0].output) / (steps[1].input - steps[0].input)
        let slopeEnd = (steps[20].output - steps[19].output) / (steps[20].input - steps[19].input)
        // Slope near midpoint (steps 9-11)
        let slopeMid = (steps[11].output - steps[9].output) / (steps[11].input - steps[9].input)

        XCTAssertGreaterThan(slopeMid, slopeStart,
                             "Midtone slope should be steeper than shadow slope in S-curve")
        XCTAssertGreaterThan(slopeMid, slopeEnd,
                             "Midtone slope should be steeper than highlight slope in S-curve")
    }

    /// All generated steps are sorted by input ascending
    func test_curveStepsSorted() {
        let linear = CurveLabFixtures.testLinearCurveSteps(count: 21)
        for i in 1..<linear.count {
            XCTAssertGreaterThanOrEqual(linear[i].input, linear[i - 1].input)
        }

        let sCurve = CurveLabFixtures.testSCurveCurveSteps(count: 21)
        for i in 1..<sCurve.count {
            XCTAssertGreaterThanOrEqual(sCurve[i].input, sCurve[i - 1].input)
        }
    }

    // ================================================================
    // MARK: - Ink Channel Math
    // ================================================================

    /// Linear channel with maxValue 65535: value at index 128 ~ 32767
    func test_inkChannel_linearRamp_valueAt128() {
        let channel = CurveLabFixtures.testInkChannelLinear(name: "K", maxValue: 65535)
        XCTAssertEqual(channel.values.count, 256)
        // index 128: (128/255) * 65535 ~ 32896
        let expected = UInt16(Double(128) / 255.0 * 65535.0 + 0.5)
        XCTAssertEqual(channel.values[128], expected)
    }

    /// Bell curve peaks at the specified peak index
    func test_inkChannel_bellCurve_peakAtCenter() {
        let channel = CurveLabFixtures.testInkChannelBellCurve(name: "LK", peak: 128, width: 40.0)
        // The maximum value should be at or very near the peak index
        let maxValue = channel.values.max()!
        XCTAssertEqual(channel.values[128], maxValue,
                       "Bell curve should peak at specified index")
        XCTAssertEqual(maxValue, 65535,
                       "Peak value should be max UInt16 range (65535)")
    }

    /// Bell curve is near-zero at index 0 and 255
    func test_inkChannel_bellCurve_zeroAtEdges() {
        let channel = CurveLabFixtures.testInkChannelBellCurve(name: "LK", peak: 128, width: 40.0)
        // At index 0: distance=128, gauss = exp(-128^2 / (2*40^2)) ~ exp(-5.12) ~ 0.006
        // So value ~ 0.006 * 65535 ~ 393
        XCTAssertLessThan(channel.values[0], 1000,
                          "Bell curve should be near-zero at index 0")
        XCTAssertLessThan(channel.values[255], 1000,
                          "Bell curve should be near-zero at index 255")
    }

    /// Empty channel has all 256 values == 0
    func test_inkChannel_empty_allZeros() {
        let channel = CurveLabFixtures.testInkChannelEmpty(name: "Unused")
        XCTAssertEqual(channel.values.count, 256)
        for (i, v) in channel.values.enumerated() {
            XCTAssertEqual(v, 0, "Index \(i) should be 0 in empty channel")
        }
        XCTAssertFalse(channel.isActive, "Empty channel should not be active")
    }

    /// Linear channel: normalized output[128] ~ 0.5
    func test_inkChannel_normalizedCurve_linearIsLinear() {
        let channel = CurveLabFixtures.testInkChannelLinear(name: "K", maxValue: 65535)
        let normalized = channel.normalizedCurve
        XCTAssertEqual(normalized.count, 256)
        // At index 128: input = 128/255 ~ 0.502, output = value/65535 ~ 0.502
        XCTAssertEqual(normalized[128].input, Double(128) / 255.0, accuracy: 1e-10)
        XCTAssertEqual(normalized[128].output, normalized[128].input, accuracy: 0.01,
                       "Linear channel normalized output should match input")
    }

    // ================================================================
    // MARK: - Ink Overlap / Transition Math
    // ================================================================

    /// When K and LK overlap in tonal range, individual channels stay in [0,1]
    /// and the combined sum stays within a reasonable range before ink limiting.
    func test_inkOverlap_twoChannels_sumNeverExceeds100() {
        // K channel: linear ramp to full density
        let kChannel = CurveLabFixtures.testInkChannelLinear(name: "K", maxValue: 65535)
        // LK channel: bell curve centered at midtones
        let lkChannel = CurveLabFixtures.testInkChannelBellCurve(name: "LK", peak: 100, width: 50.0)

        for i in 0..<256 {
            let kNorm = Double(kChannel.values[i]) / 65535.0
            let lkNorm = Double(lkChannel.values[i]) / 65535.0
            // Verify each individual channel is in [0, 1]
            XCTAssertLessThanOrEqual(kNorm, 1.0, "K normalized at \(i) must be <= 1.0")
            XCTAssertLessThanOrEqual(lkNorm, 1.0, "LK normalized at \(i) must be <= 1.0")
            XCTAssertGreaterThanOrEqual(kNorm, 0.0, "K normalized at \(i) must be >= 0.0")
            XCTAssertGreaterThanOrEqual(lkNorm, 0.0, "LK normalized at \(i) must be >= 0.0")
        }

        // With a half-strength K, the raw channel sum can exceed 1.0 where the
        // bell curve peaks (this is expected before ink-limiting is applied).
        // Verify the sum stays within a reasonable bound (< 2.0).
        let kHalf = CurveLabFixtures.testInkChannelLinear(name: "K", maxValue: 32767)
        for i in 0..<256 {
            let kNorm = Double(kHalf.values[i]) / 65535.0
            let lkNorm = Double(lkChannel.values[i]) / 65535.0
            let sum = kNorm + lkNorm
            XCTAssertLessThanOrEqual(sum, 2.0,
                                     "K+LK normalized sum at index \(i) should stay < 2.0 before ink limiting")
        }
    }

    /// At the transition point between K and LK, both have non-zero output
    func test_inkOverlap_smoothTransition() {
        let kChannel = CurveLabFixtures.testInkChannelLinear(name: "K", maxValue: 65535)
        let lkChannel = CurveLabFixtures.testInkChannelBellCurve(name: "LK", peak: 100, width: 50.0)

        // At the LK peak (index 100), K should also have non-zero output
        XCTAssertGreaterThan(kChannel.values[100], 0,
                             "K should have non-zero output at LK peak for smooth transition")
        XCTAssertGreaterThan(lkChannel.values[100], 0,
                             "LK should have non-zero output at its peak")

        // At a point between peak and edge (index 60), both should still have output
        XCTAssertGreaterThan(kChannel.values[60], 0,
                             "K should have output in transition zone")
        XCTAssertGreaterThan(lkChannel.values[60], 0,
                             "LK should have output in transition zone")
    }

    /// Sum of all 8 channel outputs at any input level, verify < some reasonable max
    func test_totalInkLoad_allChannelsSum() {
        // Build 8 channels with varied profiles
        let channels: [InkChannel] = [
            CurveLabFixtures.testInkChannelLinear(name: "K", maxValue: 16383),     // 25%
            CurveLabFixtures.testInkChannelBellCurve(name: "C", peak: 64, width: 30),
            CurveLabFixtures.testInkChannelBellCurve(name: "M", peak: 96, width: 30),
            CurveLabFixtures.testInkChannelEmpty(name: "Y"),
            CurveLabFixtures.testInkChannelBellCurve(name: "LC", peak: 128, width: 30),
            CurveLabFixtures.testInkChannelBellCurve(name: "LM", peak: 160, width: 30),
            CurveLabFixtures.testInkChannelBellCurve(name: "LK", peak: 192, width: 30),
            CurveLabFixtures.testInkChannelEmpty(name: "LLK")
        ]

        for i in 0..<256 {
            let totalNorm = channels.reduce(0.0) { sum, ch in
                sum + Double(ch.values[i]) / 65535.0
            }
            // With these conservative channel profiles, total ink should stay reasonable
            XCTAssertLessThan(totalNorm, 4.0,
                              "Total ink load at index \(i) should be < 400% normalized")
        }
    }

    // ================================================================
    // MARK: - Blocking Density / Gamma
    // ================================================================

    /// Gamma=1.0 applied to linear ramp -> still linear
    func test_gammaCurve_gamma1_isLinear() {
        for i in 0..<256 {
            let input = Double(i) / 255.0
            let output = applyGamma(input, gamma: 1.0)
            XCTAssertEqual(output, input, accuracy: 1e-10,
                           "Gamma 1.0 should be identity at index \(i)")
        }
    }

    /// Gamma=2.0: midpoint output < 0.5 (darkens midtones)
    func test_gammaCurve_gamma2_darkensMidtones() {
        let mid = applyGamma(0.5, gamma: 2.0)
        XCTAssertEqual(mid, 0.25, accuracy: 1e-10,
                       "Gamma 2.0 at 0.5 should be 0.25")
        XCTAssertLessThan(mid, 0.5,
                          "Gamma 2.0 should darken midtones (output < input)")

        // Endpoints should be unchanged
        XCTAssertEqual(applyGamma(0.0, gamma: 2.0), 0.0, accuracy: 1e-10)
        XCTAssertEqual(applyGamma(1.0, gamma: 2.0), 1.0, accuracy: 1e-10)
    }

    /// Gamma=0.5: midpoint output > 0.5 (lightens midtones)
    func test_gammaCurve_gamma05_lightensMidtones() {
        let mid = applyGamma(0.5, gamma: 0.5)
        // pow(0.5, 0.5) = sqrt(0.5) ~ 0.7071
        XCTAssertEqual(mid, sqrt(0.5), accuracy: 1e-10,
                       "Gamma 0.5 at 0.5 should be sqrt(0.5)")
        XCTAssertGreaterThan(mid, 0.5,
                             "Gamma 0.5 should lighten midtones (output > input)")

        // Endpoints should be unchanged
        XCTAssertEqual(applyGamma(0.0, gamma: 0.5), 0.0, accuracy: 1e-10)
        XCTAssertEqual(applyGamma(1.0, gamma: 0.5), 1.0, accuracy: 1e-10)
    }

    /// Highlight blocking density at 49: values below that density get zeroed
    func test_blockingDensity_clipsHighlights() {
        let channel = CurveLabFixtures.testInkChannelLinear(name: "K", maxValue: 65535)
        let blockingThreshold: UInt16 = 49  // UInt16 value threshold

        // Apply blocking: zero out any values below the threshold
        let blocked = channel.values.map { v -> UInt16 in
            v < blockingThreshold ? 0 : v
        }

        // Low-density entries (near paper white) should be zeroed
        XCTAssertEqual(blocked[0], 0, "Index 0 should be blocked (below threshold)")

        // The threshold corresponds to input index where value first reaches 49
        // Linear ramp: value[i] = round(i/255 * 65535)
        // value[0] = 0, so several low indices will be below 49
        for i in 0..<256 {
            if channel.values[i] < blockingThreshold {
                XCTAssertEqual(blocked[i], 0,
                               "Index \(i) with value \(channel.values[i]) should be blocked")
            } else {
                XCTAssertEqual(blocked[i], channel.values[i],
                               "Index \(i) above threshold should be unchanged")
            }
        }

        // High-density entries should be unaffected
        XCTAssertEqual(blocked[255], channel.values[255],
                       "Max density should not be blocked")
    }

    // ================================================================
    // MARK: - Curve Blending (Quad Curve Blending)
    // ================================================================

    /// Blend two curves 50/50 -> result ~ average of both
    func test_blendTwoCurves_equal_isAverage() {
        let curve1 = CurveLabFixtures.testInkChannelLinear(name: "Warm", maxValue: 65535).values
        let curve2 = CurveLabFixtures.testInkChannelEmpty(name: "Cool").values

        let blended = blendCurves(curve1: curve1, curve2: curve2,
                                  shadowWeight: 50, midtoneWeight: 50, highlightWeight: 50)

        for i in 0..<256 {
            let expected = Double(curve1[i]) * 0.5 + Double(curve2[i]) * 0.5
            XCTAssertEqual(Double(blended[i]), expected, accuracy: 1.0,
                           "50/50 blend at index \(i) should be average")
        }
    }

    /// Whites=100, rest=0: only highlight region comes from curve 1
    func test_blendTwoCurves_zoneWeights_highlightsOnly() {
        let curve1 = CurveLabFixtures.testInkChannelLinear(name: "Warm", maxValue: 65535).values
        let curve2 = CurveLabFixtures.testInkChannelLinear(name: "Cool", maxValue: 32767).values

        let blended = blendCurves(curve1: curve1, curve2: curve2,
                                  shadowWeight: 0, midtoneWeight: 0, highlightWeight: 100)

        // Shadows (0-84): weight=0 -> should be 100% curve2
        for i in 0..<85 {
            XCTAssertEqual(blended[i], curve2[i],
                           "Shadow zone at \(i) should be curve2 (weight=0)")
        }
        // Midtones (85-169): weight=0 -> should be 100% curve2
        for i in 85..<170 {
            XCTAssertEqual(blended[i], curve2[i],
                           "Midtone zone at \(i) should be curve2 (weight=0)")
        }
        // Highlights (170-255): weight=100 -> should be 100% curve1
        for i in 170..<256 {
            XCTAssertEqual(blended[i], curve1[i],
                           "Highlight zone at \(i) should be curve1 (weight=100)")
        }
    }

    /// All curve1 weights = 0 -> result = curve2
    func test_blendTwoCurves_allZeroWeights_isCurve2() {
        let curve1 = CurveLabFixtures.testInkChannelLinear(name: "Warm", maxValue: 65535).values
        let curve2 = CurveLabFixtures.testInkChannelLinear(name: "Cool", maxValue: 32767).values

        let blended = blendCurves(curve1: curve1, curve2: curve2,
                                  shadowWeight: 0, midtoneWeight: 0, highlightWeight: 0)

        for i in 0..<256 {
            XCTAssertEqual(blended[i], curve2[i],
                           "All-zero weights at \(i) should produce curve2")
        }
    }

    /// All curve1 weights = 100 -> result = curve1
    func test_blendTwoCurves_allMaxWeights_isCurve1() {
        let curve1 = CurveLabFixtures.testInkChannelLinear(name: "Warm", maxValue: 65535).values
        let curve2 = CurveLabFixtures.testInkChannelLinear(name: "Cool", maxValue: 32767).values

        let blended = blendCurves(curve1: curve1, curve2: curve2,
                                  shadowWeight: 100, midtoneWeight: 100, highlightWeight: 100)

        for i in 0..<256 {
            XCTAssertEqual(blended[i], curve1[i],
                           "All-max weights at \(i) should produce curve1")
        }
    }

    // ================================================================
    // MARK: - Curve Export (QTR .txt format)
    // ================================================================

    /// Exported text has 256 data lines (plus header comments)
    func test_exportLinearCurve_256Lines() {
        let steps = CurveLabFixtures.testLinearCurveSteps(count: 21)
        let exported = exportCurveTxt(steps: steps)
        let lines = exported.components(separatedBy: "\n")

        // Count non-comment, non-empty lines
        let dataLines = lines.filter { !$0.hasPrefix("#") && !$0.isEmpty }
        XCTAssertEqual(dataLines.count, 256,
                       "Export should have exactly 256 data lines")
    }

    /// All exported values are integers 0-255
    func test_exportLinearCurve_valuesRange0to255() {
        let steps = CurveLabFixtures.testLinearCurveSteps(count: 21)
        let exported = exportCurveTxt(steps: steps)
        let lines = exported.components(separatedBy: "\n")
        let dataLines = lines.filter { !$0.hasPrefix("#") && !$0.isEmpty }

        for (i, line) in dataLines.enumerated() {
            guard let value = Int(line) else {
                XCTFail("Line \(i) is not an integer: '\(line)'")
                continue
            }
            XCTAssertGreaterThanOrEqual(value, 0, "Value at line \(i) should be >= 0")
            XCTAssertLessThanOrEqual(value, 255, "Value at line \(i) should be <= 255")
        }
    }

    /// Linear curve: first value = 0, last = 255
    func test_exportLinearCurve_firstIsZero_lastIs255() {
        let steps = CurveLabFixtures.testLinearCurveSteps(count: 256)
        let exported = exportCurveTxt(steps: steps)
        let lines = exported.components(separatedBy: "\n")
        let dataLines = lines.filter { !$0.hasPrefix("#") && !$0.isEmpty }

        XCTAssertEqual(dataLines.count, 256)
        XCTAssertEqual(Int(dataLines.first!), 0, "First exported value should be 0")
        XCTAssertEqual(Int(dataLines.last!), 255, "Last exported value should be 255")
    }

    /// S-curve export: value at line 128 != 128
    func test_exportSCurve_midpointNotHalf() {
        let steps = CurveLabFixtures.testSCurveCurveSteps(count: 21)
        let exported = exportCurveTxt(steps: steps)
        let lines = exported.components(separatedBy: "\n")
        let dataLines = lines.filter { !$0.hasPrefix("#") && !$0.isEmpty }

        XCTAssertEqual(dataLines.count, 256)
        // Line at index 64 (quarter point) should differ from 64 for an S-curve
        let quarterValue = Int(dataLines[64])!
        XCTAssertNotEqual(quarterValue, 64,
                          "S-curve at input 64/255 should not output 64 (that would be linear)")
    }
}
