// CurveIOTests.swift
// HoehnPhotosOrganizerTests
//
// Tests curve file I/O: reading/writing .quad files to disk, scanning directories,
// exporting curves, and the OpenRIP integration path.

import XCTest
@testable import HoehnPhotosOrganizer

final class CurveIOTests: XCTestCase {

    private var tempDir: URL!

    override func setUp() {
        super.setUp()
        tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("CurveIOTests-\(UUID().uuidString)")
        try? FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
    }

    override func tearDown() {
        try? FileManager.default.removeItem(at: tempDir)
        super.tearDown()
    }

    // MARK: - Helpers

    /// Serialize a QTRQuadFile back to .quad format string.
    private func serializeQuadFile(_ quad: QTRQuadFile) -> String {
        var lines: [String] = []
        lines.append("## QuadToneRIP K,C,M,Y,LC,LM,LK,LLK")
        // Re-emit non-header comments, but skip channel marker lines
        // (they will be re-added below for each channel section)
        for comment in quad.comments where !comment.starts(with: "##") {
            let lower = comment.lowercased()
            let isChannelMarker = lower.contains("curve")
                && !lower.contains("linearized")
                && !lower.contains("max")
            if !isChannelMarker {
                lines.append(comment)
            }
        }
        let channelNames = ["K", "C", "M", "Y", "LC", "LM", "LK", "LLK"]
        for (i, channel) in quad.channels.enumerated() {
            lines.append("# \(channelNames[i]) curve")
            for value in channel.values {
                lines.append("\(value)")
            }
        }
        return lines.joined(separator: "\n")
    }

    /// Generate a K-only channel with a gamma curve applied.
    private func generateGammaKChannel(gamma: Double, maxValue: UInt16 = 29695) -> [UInt16] {
        (0..<256).map { i in
            let t = Double(i) / 255.0
            let v = pow(t, gamma)
            return UInt16(min(Double(maxValue) * v, Double(UInt16.max)))
        }
    }

    /// Build a full .quad string with only K active, using the given K values.
    private func buildKOnlyQuadString(kValues: [UInt16]) -> String {
        var lines: [String] = []
        lines.append("## QuadToneRIP K,C,M,Y,LC,LM,LK,LLK")
        lines.append("# K curve")
        for v in kValues {
            lines.append("\(v)")
        }
        let zeroChannelNames = ["C", "M", "Y", "LC", "LM", "LK", "LLK"]
        for name in zeroChannelNames {
            lines.append("# \(name) Curve")
            for _ in 0..<256 {
                lines.append("0")
            }
        }
        return lines.joined(separator: "\n")
    }

    /// Generate a 256-line curve export string (integer values).
    private func generateCurveTxtString(gamma: Double = 1.0, maxValue: Int = 29695) -> String {
        var lines: [String] = []
        lines.append("# Curve export")
        lines.append("# Generated by CurveIOTests")
        for i in 0..<256 {
            let t = Double(i) / 255.0
            let v = pow(t, gamma)
            let intVal = Int(Double(maxValue) * v)
            lines.append("\(intVal)")
        }
        return lines.joined(separator: "\n")
    }

    /// Build a measurement .txt string with the given number of steps.
    private func buildMeasurementString(steps: Int) -> String {
        var lines: [String] = []
        lines.append("QuadToneProfiler Measurement Data File")
        lines.append("Step\tL*\ta*\tb*")
        for i in 0..<steps {
            let lStar = 95.0 - (Double(i) / Double(max(steps - 1, 1))) * 90.0
            let aStar = 0.1 + Double(i) * 0.03
            let bStar = 1.5 + Double(i) * 0.1
            lines.append("\(i + 1)\t\(String(format: "%.2f", lStar))\t\(String(format: "%.2f", aStar))\t\(String(format: "%.2f", bStar))")
        }
        return lines.joined(separator: "\n")
    }

    // MARK: - Write and Read Quad Files

    func test_writeAndReadQuadFile_roundTrip() throws {
        let quadContent = testLinearKOnlyQuad
        let fileURL = tempDir.appendingPathComponent("linear-k.quad")
        try quadContent.write(to: fileURL, atomically: true, encoding: .utf8)

        let parsed = try QTRFileParser.parseQuadFile(at: fileURL)
        let kValues = parsed.channels[0].values

        // K channel should be a linear ramp: starts at 0, ends near 29695
        XCTAssertEqual(kValues[0], 0)
        XCTAssertEqual(Double(kValues[255]), 29695.0, accuracy: 200.0)
        // Midpoint should be roughly half
        XCTAssertEqual(Double(kValues[128]), 14847.0, accuracy: 300.0)
    }

    func test_writeMultipleQuadFiles_scanFindsAll() throws {
        for name in ["alpha.quad", "beta.quad", "gamma.quad"] {
            let url = tempDir.appendingPathComponent(name)
            try testLinearKOnlyQuad.write(to: url, atomically: true, encoding: .utf8)
        }

        let results = QTRFileParser.scanQuadDirectory(at: tempDir.path)
        XCTAssertEqual(results.count, 3)
    }

    func test_scanQuadDirectory_ignoresNonQuadFiles() throws {
        let quadURL = tempDir.appendingPathComponent("real.quad")
        let txtURL = tempDir.appendingPathComponent("notes.txt")
        try testLinearKOnlyQuad.write(to: quadURL, atomically: true, encoding: .utf8)
        try "not a quad file".write(to: txtURL, atomically: true, encoding: .utf8)

        let results = QTRFileParser.scanQuadDirectory(at: tempDir.path)
        XCTAssertEqual(results.count, 1)
        XCTAssertEqual(results[0].lastPathComponent, "real.quad")
    }

    func test_scanQuadDirectory_returnsSorted() throws {
        for name in ["b.quad", "a.quad", "c.quad"] {
            let url = tempDir.appendingPathComponent(name)
            try "dummy".write(to: url, atomically: true, encoding: .utf8)
        }

        let results = QTRFileParser.scanQuadDirectory(at: tempDir.path)
        let names = results.map { $0.lastPathComponent }
        XCTAssertEqual(names, ["a.quad", "b.quad", "c.quad"])
    }

    // MARK: - Write and Read Measurement Files

    func test_writeAndReadMeasurement_roundTrip() throws {
        let content = testMeasurement21Steps
        let fileURL = tempDir.appendingPathComponent("meas.txt")
        try content.write(to: fileURL, atomically: true, encoding: .utf8)

        let parsed = try QTRFileParser.parseMeasurement(at: fileURL)
        XCTAssertEqual(parsed.stepCount, 21)
        // Paper white should be around 95
        XCTAssertNotNil(parsed.paperWhiteL)
        XCTAssertEqual(parsed.paperWhiteL!, 95.2, accuracy: 0.1)
        // Dmax should be around 5
        XCTAssertNotNil(parsed.dMaxL)
        XCTAssertEqual(parsed.dMaxL!, 5.1, accuracy: 0.1)
    }

    func test_scanMeasurementDirectory_findsTxtFiles() throws {
        for name in ["meas1.txt", "meas2.txt", "meas3.txt"] {
            let url = tempDir.appendingPathComponent(name)
            try buildMeasurementString(steps: 11).write(to: url, atomically: true, encoding: .utf8)
        }

        let results = QTRFileParser.scanMeasurementDirectory(at: tempDir.path)
        XCTAssertEqual(results.count, 3)
    }

    func test_scanMeasurementDirectory_ignoresQuadFiles() throws {
        let quadURL = tempDir.appendingPathComponent("profile.quad")
        try testLinearKOnlyQuad.write(to: quadURL, atomically: true, encoding: .utf8)

        let results = QTRFileParser.scanMeasurementDirectory(at: tempDir.path)
        XCTAssertEqual(results.count, 0)
    }

    // MARK: - Curve Export to Disk

    func test_exportCurveTxtToDisk_writesFile() throws {
        let content = generateCurveTxtString(gamma: 1.0)
        let fileURL = tempDir.appendingPathComponent("exported-curve.txt")
        try content.write(to: fileURL, atomically: true, encoding: .utf8)

        XCTAssertTrue(FileManager.default.fileExists(atPath: fileURL.path))
        let readBack = try String(contentsOf: fileURL, encoding: .utf8)
        XCTAssertEqual(readBack, content)
    }

    func test_exportCurveTxtToDisk_valuesAreIntegers() throws {
        let content = generateCurveTxtString(gamma: 1.5)
        let fileURL = tempDir.appendingPathComponent("int-curve.txt")
        try content.write(to: fileURL, atomically: true, encoding: .utf8)

        let readBack = try String(contentsOf: fileURL, encoding: .utf8)
        let lines = readBack.components(separatedBy: .newlines)
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty || trimmed.hasPrefix("#") { continue }
            XCTAssertNotNil(
                Int(trimmed),
                "Non-comment line should parse as Int, got: '\(trimmed)'"
            )
        }
    }

    func test_exportCurveTxtToDisk_has256DataLines() throws {
        let content = generateCurveTxtString(gamma: 1.0)
        let fileURL = tempDir.appendingPathComponent("256-curve.txt")
        try content.write(to: fileURL, atomically: true, encoding: .utf8)

        let readBack = try String(contentsOf: fileURL, encoding: .utf8)
        let lines = readBack.components(separatedBy: .newlines)
        let dataLines = lines.filter { line in
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            return !trimmed.isEmpty && !trimmed.hasPrefix("#")
        }
        XCTAssertEqual(dataLines.count, 256)
    }

    // MARK: - Multiple Curve Versions

    func test_saveCurveVersions_incrementalNaming() throws {
        let names = ["MyProcess.quad", "MyProcess-v2.quad", "MyProcess-v3.quad"]
        for name in names {
            let url = tempDir.appendingPathComponent(name)
            let kValues = generateGammaKChannel(gamma: 1.0)
            let content = buildKOnlyQuadString(kValues: kValues)
            try content.write(to: url, atomically: true, encoding: .utf8)
        }

        for name in names {
            let path = tempDir.appendingPathComponent(name).path
            XCTAssertTrue(
                FileManager.default.fileExists(atPath: path),
                "File \(name) should exist"
            )
        }
    }

    func test_saveCurveVersions_eachParseableIndependently() throws {
        let names = ["MyProcess.quad", "MyProcess-v2.quad", "MyProcess-v3.quad"]
        let gammas = [1.0, 0.5, 2.0]

        for (i, name) in names.enumerated() {
            let url = tempDir.appendingPathComponent(name)
            let kValues = generateGammaKChannel(gamma: gammas[i])
            let content = buildKOnlyQuadString(kValues: kValues)
            try content.write(to: url, atomically: true, encoding: .utf8)
        }

        for name in names {
            let url = tempDir.appendingPathComponent(name)
            let parsed = try QTRFileParser.parseQuadFile(at: url)
            XCTAssertEqual(parsed.channels.count, 8, "Parsed \(name) should have 8 channels")
            XCTAssertEqual(parsed.channels[0].values.count, 256, "K channel in \(name) should have 256 values")
        }
    }

    func test_saveCurveVersions_differentKValues() throws {
        let names = ["MyProcess.quad", "MyProcess-v2.quad", "MyProcess-v3.quad"]
        let gammas = [1.0, 0.5, 2.0]  // linear, lighter, darker

        var parsedQuads: [QTRQuadFile] = []

        for (i, name) in names.enumerated() {
            let url = tempDir.appendingPathComponent(name)
            let kValues = generateGammaKChannel(gamma: gammas[i])
            let content = buildKOnlyQuadString(kValues: kValues)
            try content.write(to: url, atomically: true, encoding: .utf8)
            let parsed = try QTRFileParser.parseQuadFile(at: url)
            parsedQuads.append(parsed)
        }

        // Compare midpoint (index 128) values across versions
        let midLinear = parsedQuads[0].channels[0].values[128]
        let midLight = parsedQuads[1].channels[0].values[128]   // gamma 0.5 = lighter
        let midDark = parsedQuads[2].channels[0].values[128]    // gamma 2.0 = darker

        // gamma 0.5 midpoint should be higher than linear midpoint (more ink early)
        XCTAssertGreaterThan(midLight, midLinear, "Gamma 0.5 midpoint should be above linear")
        // gamma 2.0 midpoint should be lower than linear midpoint (less ink early)
        XCTAssertLessThan(midDark, midLinear, "Gamma 2.0 midpoint should be below linear")
    }

    // MARK: - Quad File Serialization

    func test_serializeQuadFile_headerFormat() throws {
        let quad = try QTRFileParser.parseQuadFile(
            content: testLinearKOnlyQuad,
            fileName: "test.quad"
        )
        let serialized = serializeQuadFile(quad)
        XCTAssertTrue(
            serialized.hasPrefix("## QuadToneRIP K,C,M,Y,LC,LM,LK,LLK"),
            "Serialized .quad should start with the standard QTR header"
        )
    }

    func test_serializeQuadFile_channelMarkers() throws {
        let quad = try QTRFileParser.parseQuadFile(
            content: testLinearKOnlyQuad,
            fileName: "test.quad"
        )
        let serialized = serializeQuadFile(quad)
        let lower = serialized.lowercased()

        let expectedChannels = ["k curve", "c curve", "m curve", "y curve",
                                "lc curve", "lm curve", "lk curve", "llk curve"]
        for ch in expectedChannels {
            XCTAssertTrue(
                lower.contains(ch),
                "Serialized .quad should contain channel marker '\(ch)'"
            )
        }
    }

    func test_serializeQuadFile_256ValuesPerChannel() throws {
        let quad = try QTRFileParser.parseQuadFile(
            content: testLinearKOnlyQuad,
            fileName: "test.quad"
        )
        let serialized = serializeQuadFile(quad)
        let lines = serialized.components(separatedBy: .newlines)

        // Count data lines per channel section
        var channelDataCounts: [Int] = []
        var currentCount = 0
        var inChannel = false

        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.hasPrefix("#") {
                let lower = trimmed.lowercased()
                // Match the production parser's channel marker detection:
                // must contain "curve", must NOT contain "quadtonerip", "linearized", or "max"
                if lower.contains("curve") && !lower.contains("quadtonerip")
                    && !lower.contains("linearized") && !lower.contains("max") {
                    if inChannel {
                        channelDataCounts.append(currentCount)
                    }
                    currentCount = 0
                    inChannel = true
                }
                continue
            }
            if inChannel && !trimmed.isEmpty && UInt16(trimmed) != nil {
                currentCount += 1
            }
        }
        // Flush last channel
        if inChannel {
            channelDataCounts.append(currentCount)
        }

        XCTAssertEqual(channelDataCounts.count, 8, "Should have 8 channel sections")
        for (i, count) in channelDataCounts.enumerated() {
            XCTAssertEqual(count, 256, "Channel \(i) should have 256 data lines, got \(count)")
        }
    }

    func test_serializeQuadFile_roundTrip() throws {
        let original = try QTRFileParser.parseQuadFile(
            content: testLinearKOnlyQuad,
            fileName: "test.quad"
        )

        // Serialize -> parse -> serialize -> parse
        let serialized1 = serializeQuadFile(original)
        let parsed1 = try QTRFileParser.parseQuadFile(content: serialized1, fileName: "test.quad")
        let serialized2 = serializeQuadFile(parsed1)
        let parsed2 = try QTRFileParser.parseQuadFile(content: serialized2, fileName: "test.quad")

        // Both parsed results should have identical channel values
        for chIdx in 0..<8 {
            let vals1 = parsed1.channels[chIdx].values
            let vals2 = parsed2.channels[chIdx].values
            XCTAssertEqual(vals1.count, vals2.count, "Channel \(chIdx) value count mismatch")
            for vIdx in 0..<vals1.count {
                XCTAssertEqual(
                    vals1[vIdx], vals2[vIdx],
                    "Channel \(chIdx) value mismatch at index \(vIdx): \(vals1[vIdx]) vs \(vals2[vIdx])"
                )
            }
        }
    }

    // MARK: - Production Serializer Round-Trip

    func test_productionSerializer_roundTrip_identicalChannelValues() throws {
        // Parse a known-good quad string
        let original = try QTRFileParser.parseQuadFile(
            content: testLinearKOnlyQuad,
            fileName: "roundtrip.quad"
        )

        // Serialize with the PRODUCTION serializer (QTRFileParser.serializeQuadFile)
        let serialized = QTRFileParser.serializeQuadFile(original)

        // Parse the serialized output
        let reparsed = try QTRFileParser.parseQuadFile(
            content: serialized,
            fileName: "roundtrip.quad"
        )

        // Assert identical channel values
        XCTAssertEqual(reparsed.channels.count, original.channels.count,
                       "Channel count should match after round-trip")
        for chIdx in 0..<original.channels.count {
            let origVals = original.channels[chIdx].values
            let newVals = reparsed.channels[chIdx].values
            XCTAssertEqual(origVals.count, newVals.count,
                           "Channel \(original.channels[chIdx].name) value count mismatch")
            for vIdx in 0..<origVals.count {
                XCTAssertEqual(
                    origVals[vIdx], newVals[vIdx],
                    "Channel \(original.channels[chIdx].name) value mismatch at index \(vIdx): " +
                    "expected \(origVals[vIdx]), got \(newVals[vIdx])"
                )
            }
        }
    }

    func test_productionSerializer_roundTrip_multiChannel() throws {
        // Build a quad with K + C active (two non-zero channels)
        let kValues = generateGammaKChannel(gamma: 1.0)
        let cValues = generateGammaKChannel(gamma: 0.8, maxValue: 20000)
        var channelArrays: [[UInt16]] = Array(repeating: Array(repeating: UInt16(0), count: 256), count: 8)
        channelArrays[0] = kValues
        channelArrays[1] = cValues

        let channelNames = ["K", "C", "M", "Y", "LC", "LM", "LK", "LLK"]
        let channels = channelArrays.enumerated().map { i, vals in
            InkChannel(name: channelNames[i], values: vals)
        }
        let quad = QTRQuadFile(
            fileName: "multi.quad",
            comments: ["## QuadToneRIP K,C,M,Y,LC,LM,LK,LLK"],
            channels: channels
        )

        // Serialize → parse → assert identical
        let serialized = QTRFileParser.serializeQuadFile(quad)
        let reparsed = try QTRFileParser.parseQuadFile(content: serialized, fileName: "multi.quad")

        for chIdx in 0..<8 {
            let origVals = quad.channels[chIdx].values
            let newVals = reparsed.channels[chIdx].values
            for vIdx in 0..<256 {
                XCTAssertEqual(
                    origVals[vIdx], newVals[vIdx],
                    "Channel \(channelNames[chIdx]) mismatch at \(vIdx)"
                )
            }
        }
    }

    // MARK: - OpenRIP Integration (real files on this system)

    func test_openRIPPPDExists() {
        let path = "/Library/Printers/OpenRIP/ppd/OpenRIP-P800.ppd"
        XCTAssertTrue(
            FileManager.default.fileExists(atPath: path),
            "OpenRIP PPD should exist at \(path)"
        )
    }

    func test_openRIPFilterExists() {
        let path = "/Library/Printers/OpenRIP/filter/quadtoneprint-open"
        XCTAssertTrue(
            FileManager.default.fileExists(atPath: path),
            "OpenRIP filter should exist at \(path)"
        )
    }

    func test_realQuadDirectory_hasQuadFiles() {
        let quadDir = "/Library/Printers/QTR/quadtone/QuadP800-DN"
        let results = QTRFileParser.scanQuadDirectory(at: quadDir)
        XCTAssertGreaterThan(results.count, 0, "QuadP800-DN directory should contain .quad files")
    }

    func test_realQuadDirectory_containsCyanotypeFiles() {
        let quadDir = "/Library/Printers/QTR/quadtone/QuadP800-DN"
        let results = QTRFileParser.scanQuadDirectory(at: quadDir)
        let names = results.map { $0.lastPathComponent }
        let hasCyanotype = names.contains(where: { $0.contains("Cyanotype") })
        XCTAssertTrue(hasCyanotype, "QuadP800-DN should contain at least one Cyanotype .quad file")
    }

    func test_realQuadDirectory_containsDTPFiles() {
        let quadDir = "/Library/Printers/QTR/quadtone/QuadP800-DN"
        let results = QTRFileParser.scanQuadDirectory(at: quadDir)
        let names = results.map { $0.lastPathComponent }
        let hasDTP = names.contains(where: { $0.contains("DTP") })
        XCTAssertTrue(hasDTP, "QuadP800-DN should contain at least one DTP .quad file")
    }

    func test_realQuadFile_parsesSuccessfully() throws {
        let quadDir = "/Library/Printers/QTR/quadtone/QuadP800-DN"
        let results = QTRFileParser.scanQuadDirectory(at: quadDir)
        guard let firstURL = results.first else {
            XCTFail("No .quad files found in QuadP800-DN to test parsing")
            return
        }

        let parsed = try QTRFileParser.parseQuadFile(at: firstURL)
        XCTAssertEqual(parsed.channels.count, 8, "Parsed real .quad should have 8 channels")
        XCTAssertGreaterThanOrEqual(
            parsed.activeChannels.count, 1,
            "Parsed real .quad should have at least 1 active channel"
        )
    }

    // MARK: - Gamma Curve Variants

    func test_writeGammaCurves_linear() throws {
        let kValues = generateGammaKChannel(gamma: 1.0)
        let content = buildKOnlyQuadString(kValues: kValues)
        let url = tempDir.appendingPathComponent("linear.quad")
        try content.write(to: url, atomically: true, encoding: .utf8)

        let parsed = try QTRFileParser.parseQuadFile(at: url)
        let k = parsed.channels[0].values

        // Linear: values should step roughly evenly. Index 1 ~ 116, index 2 ~ 232
        XCTAssertEqual(k[0], 0)
        XCTAssertEqual(Double(k[1]), 116.0, accuracy: 5.0)
        XCTAssertEqual(Double(k[2]), 232.0, accuracy: 10.0)
    }

    func test_writeGammaCurves_dark() throws {
        let linearK = generateGammaKChannel(gamma: 1.0)
        let darkK = generateGammaKChannel(gamma: 2.0)
        let content = buildKOnlyQuadString(kValues: darkK)
        let url = tempDir.appendingPathComponent("dark.quad")
        try content.write(to: url, atomically: true, encoding: .utf8)

        let parsed = try QTRFileParser.parseQuadFile(at: url)
        let midDark = parsed.channels[0].values[128]
        let midLinear = linearK[128]

        // Gamma 2.0 (darker midtones) -> midpoint value should be less than linear
        XCTAssertLessThan(
            midDark, midLinear,
            "Gamma 2.0 midpoint (\(midDark)) should be less than linear midpoint (\(midLinear))"
        )
    }

    func test_writeGammaCurves_light() throws {
        let linearK = generateGammaKChannel(gamma: 1.0)
        let lightK = generateGammaKChannel(gamma: 0.5)
        let content = buildKOnlyQuadString(kValues: lightK)
        let url = tempDir.appendingPathComponent("light.quad")
        try content.write(to: url, atomically: true, encoding: .utf8)

        let parsed = try QTRFileParser.parseQuadFile(at: url)
        let midLight = parsed.channels[0].values[128]
        let midLinear = linearK[128]

        // Gamma 0.5 (lighter midtones) -> midpoint value should be greater than linear
        XCTAssertGreaterThan(
            midLight, midLinear,
            "Gamma 0.5 midpoint (\(midLight)) should be greater than linear midpoint (\(midLinear))"
        )
    }

    func test_writeGammaCurves_allParseable() throws {
        let gammas = [1.0, 0.5, 2.0]
        let names = ["linear.quad", "light.quad", "dark.quad"]

        for (i, name) in names.enumerated() {
            let kValues = generateGammaKChannel(gamma: gammas[i])
            let content = buildKOnlyQuadString(kValues: kValues)
            let url = tempDir.appendingPathComponent(name)
            try content.write(to: url, atomically: true, encoding: .utf8)
        }

        for name in names {
            let url = tempDir.appendingPathComponent(name)
            let parsed = try QTRFileParser.parseQuadFile(at: url)
            XCTAssertEqual(parsed.channels.count, 8, "\(name) should parse to 8 channels")
            XCTAssertTrue(parsed.channels[0].isActive, "K channel in \(name) should be active")
        }
    }
}
