import SwiftUI
import UniformTypeIdentifiers

// MARK: - CurveBuilderView

/// Build QTR linearization curves from scanned targets.
/// Left: target image + curve graph. Right: chat panel.
struct CurveBuilderView: View {

    @ObservedObject var viewModel: CurveLabViewModel

    @State private var isDragOver = false

    var body: some View {
        HStack(spacing: 0) {
            // Main content
            VStack(spacing: 0) {
                builderToolbar
                Divider()

                HStack(spacing: 0) {
                    // Left: target & settings
                    builderSidebar
                        .frame(width: 240)

                    Divider()

                    // Center: curve graph + target image
                    builderCanvas
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                }
            }

            Divider()

            // Right: chat
            CurveLabChatPanel(viewModel: viewModel, isCollapsed: .constant(false))
        }
    }

    // MARK: - Load image

    private func openTargetPanel() {
        let panel = NSOpenPanel()
        panel.allowedContentTypes = [.jpeg, .tiff, .png, .bmp]
        panel.allowsMultipleSelection = false
        panel.canChooseDirectories = false
        panel.message = "Select a scanned target image"
        panel.prompt = "Load"

        guard panel.runModal() == .OK, let url = panel.url else { return }
        loadTargetImage(from: url)
    }

    private func loadTargetImage(from url: URL) {
        let accessing = url.startAccessingSecurityScopedResource()
        defer { if accessing { url.stopAccessingSecurityScopedResource() } }

        guard let image = NSImage(contentsOf: url) else { return }
        viewModel.builderTargetImage = image

        // If it's a measurement .txt, also parse it
        if url.pathExtension.lowercased() == "txt" {
            if let meas = try? QTRFileParser.parseMeasurement(at: url) {
                viewModel.builderSteps = meas.steps.enumerated().map { i, step in
                    CurveStep(
                        input: Double(i) / Double(max(meas.steps.count - 1, 1)),
                        output: step.labL / 100.0
                    )
                }
            }
        }
    }

    private func handleDrop(providers: [NSItemProvider]) -> Bool {
        for provider in providers {
            // Try file URL first
            if provider.hasItemConformingToTypeIdentifier(UTType.fileURL.identifier) {
                provider.loadItem(forTypeIdentifier: UTType.fileURL.identifier, options: nil) { data, _ in
                    guard let data = data as? Data,
                          let url = URL(dataRepresentation: data, relativeTo: nil) else { return }
                    DispatchQueue.main.async {
                        loadTargetImage(from: url)
                    }
                }
                return true
            }
            // Try image data directly
            if provider.hasItemConformingToTypeIdentifier(UTType.image.identifier) {
                provider.loadItem(forTypeIdentifier: UTType.image.identifier, options: nil) { data, _ in
                    var image: NSImage?
                    if let data = data as? Data {
                        image = NSImage(data: data)
                    } else if let url = data as? URL {
                        image = NSImage(contentsOf: url)
                    }
                    if let image {
                        DispatchQueue.main.async {
                            viewModel.builderTargetImage = image
                        }
                    }
                }
                return true
            }
        }
        return false
    }

    // MARK: - Export

    private func exportCurveTxt() {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.plainText]
        panel.nameFieldStringValue = "custom-curve.txt"
        panel.message = "Save QTR linearization curve"
        panel.prompt = "Export"
        panel.begin { response in
            if response == .OK, let url = panel.url {
                let content = generateCurveTxtContent()
                try? content.write(to: url, atomically: true, encoding: .utf8)
            }
        }
    }

    private func generateCurveTxtContent() -> String {
        var lines: [String] = []
        lines.append("# QTR Linearization Curve")
        lines.append("# Generated by HoehnPhotos CurveLab")
        lines.append("# Process: \(viewModel.selectedProcess.rawValue)")
        lines.append("# Values: 256 ink density steps (0 = no ink, 255 = full ink)")
        lines.append("")

        if viewModel.builderSteps.isEmpty {
            // No data — emit a linear ramp as a safe placeholder
            for i in 0..<256 {
                lines.append("\(i)")
            }
        } else {
            // Interpolate measured CurveStep data to 256 output values.
            // CurveStep.input/output are both 0.0–1.0.
            let sorted = viewModel.builderSteps.sorted(by: { $0.input < $1.input })
            for i in 0..<256 {
                let t = Double(i) / 255.0   // input position (0–1)
                let output = interpolate(t: t, steps: sorted)
                let value = Int(output * 255.0 + 0.5)
                lines.append("\(min(max(value, 0), 255))")
            }
        }

        return lines.joined(separator: "\n")
    }

    /// Linear interpolation over sorted CurveStep array for a given t in [0,1].
    private func interpolate(t: Double, steps: [CurveStep]) -> Double {
        guard !steps.isEmpty else { return t }
        if t <= steps.first!.input { return steps.first!.output }
        if t >= steps.last!.input  { return steps.last!.output  }

        for i in 0..<(steps.count - 1) {
            let lo = steps[i]
            let hi = steps[i + 1]
            if t >= lo.input && t <= hi.input {
                let span = hi.input - lo.input
                guard span > 0 else { return lo.output }
                let fraction = (t - lo.input) / span
                return lo.output + fraction * (hi.output - lo.output)
            }
        }
        return steps.last!.output
    }

    // MARK: - Toolbar

    private var builderToolbar: some View {
        HStack(spacing: 12) {
            Button {
                openTargetPanel()
            } label: {
                Label("Load Target", systemImage: "doc.badge.plus")
                    .font(.system(size: 12))
            }
            .buttonStyle(.bordered)
            .controlSize(.small)

            Button {
                // TODO: read patches from target
            } label: {
                Label("Read Patches", systemImage: "eyedropper")
                    .font(.system(size: 12))
            }
            .buttonStyle(.bordered)
            .controlSize(.small)
            .disabled(viewModel.builderTargetImage == nil)

            Button {
                // TODO: generate curve
            } label: {
                Label("Generate Curve", systemImage: "waveform.path.ecg")
                    .font(.system(size: 12))
            }
            .buttonStyle(.bordered)
            .controlSize(.small)
            .disabled(viewModel.builderSteps.isEmpty)

            Spacer()

            if viewModel.builderTargetImage != nil {
                Button {
                    viewModel.builderTargetImage = nil
                    viewModel.builderSteps = []
                } label: {
                    Label("Clear", systemImage: "xmark")
                        .font(.system(size: 12))
                }
                .buttonStyle(.bordered)
                .controlSize(.small)
            }

            Button {
                exportCurveTxt()
            } label: {
                Label("Export .txt", systemImage: "square.and.arrow.up")
                    .font(.system(size: 12))
            }
            .buttonStyle(.borderedProminent)
            .controlSize(.small)
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 8)
        .background(Color(nsColor: .controlBackgroundColor))
    }

    // MARK: - Left Sidebar

    private var builderSidebar: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                // Process picker
                VStack(alignment: .leading, spacing: 6) {
                    Text("PROCESS")
                        .font(.system(size: 10, weight: .semibold))
                        .foregroundStyle(.secondary)

                    Picker("", selection: $viewModel.selectedProcess) {
                        ForEach(PrintProcess.allCases) { process in
                            Text(process.rawValue).tag(process)
                        }
                    }
                    .labelsHidden()
                }

                // Ink tone
                VStack(alignment: .leading, spacing: 6) {
                    Text("INK TONE")
                        .font(.system(size: 10, weight: .semibold))
                        .foregroundStyle(.secondary)

                    HStack(spacing: 8) {
                        ForEach(InkTone.allCases) { tone in
                            Button {
                                // TODO: set ink tone
                            } label: {
                                VStack(spacing: 3) {
                                    Circle()
                                        .fill(tone.color.opacity(0.7))
                                        .frame(width: 20, height: 20)
                                    Text(tone.rawValue)
                                        .font(.system(size: 9))
                                }
                            }
                            .buttonStyle(.plain)
                        }
                    }
                }

                Divider()

                // Step count
                VStack(alignment: .leading, spacing: 6) {
                    Text("STEP WEDGE")
                        .font(.system(size: 10, weight: .semibold))
                        .foregroundStyle(.secondary)

                    if viewModel.builderSteps.isEmpty {
                        Text("No data loaded")
                            .font(.system(size: 12))
                            .foregroundStyle(.tertiary)
                    } else {
                        Text("\(viewModel.builderSteps.count) steps")
                            .font(.system(size: 12))
                    }
                }

                Divider()

                // Curve data
                if !viewModel.builderSteps.isEmpty {
                    VStack(alignment: .leading, spacing: 6) {
                        Text("CURVE DATA")
                            .font(.system(size: 10, weight: .semibold))
                            .foregroundStyle(.secondary)

                        ForEach(viewModel.builderSteps) { step in
                            HStack {
                                Text(String(format: "%.0f%%", step.input * 100))
                                    .font(.system(size: 10, design: .monospaced))
                                    .frame(width: 36, alignment: .trailing)
                                Rectangle()
                                    .fill(Color.primary.opacity(0.3))
                                    .frame(height: 1)
                                Text(String(format: "%.0f%%", step.output * 100))
                                    .font(.system(size: 10, design: .monospaced))
                                    .frame(width: 36, alignment: .trailing)
                            }
                        }
                    }
                }

                Spacer()
            }
            .padding(12)
        }
        .background(Color(nsColor: .windowBackgroundColor))
    }

    // MARK: - Center Canvas

    private var builderCanvas: some View {
        ZStack {
            VStack(spacing: 16) {
                if let target = viewModel.builderTargetImage {
                    // Scanned target preview
                    Image(nsImage: target)
                        .resizable()
                        .aspectRatio(contentMode: .fit)
                        .frame(maxHeight: 200)
                        .clipShape(RoundedRectangle(cornerRadius: 8))
                        .overlay(
                            RoundedRectangle(cornerRadius: 8)
                                .strokeBorder(Color.secondary.opacity(0.3), lineWidth: 1)
                        )

                    Text("Scanned Target")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                // Curve graph
                curveGraphPlaceholder
                    .frame(maxWidth: .infinity, maxHeight: .infinity)

                if viewModel.builderTargetImage == nil && viewModel.builderSteps.isEmpty {
                    emptyBuilderState
                }
            }
            .padding(20)

            // Drag overlay
            if isDragOver {
                RoundedRectangle(cornerRadius: 12)
                    .strokeBorder(Color.accentColor, lineWidth: 3)
                    .background(
                        RoundedRectangle(cornerRadius: 12)
                            .fill(Color.accentColor.opacity(0.08))
                    )
                    .overlay(
                        VStack(spacing: 8) {
                            Image(systemName: "arrow.down.doc")
                                .font(.system(size: 36))
                                .foregroundStyle(Color.accentColor)
                            Text("Drop scanned target image")
                                .font(.system(size: 14, weight: .medium))
                                .foregroundStyle(Color.accentColor)
                        }
                    )
                    .padding(8)
            }
        }
        .onDrop(of: [.fileURL, .image], isTargeted: $isDragOver) { providers in
            handleDrop(providers: providers)
        }
    }

    private var curveGraphPlaceholder: some View {
        ZStack {
            // Grid
            Canvas { context, size in
                let gridColor = Color.secondary.opacity(0.15)
                let steps = 10
                for i in 0...steps {
                    let x = CGFloat(i) / CGFloat(steps) * size.width
                    let y = CGFloat(i) / CGFloat(steps) * size.height
                    context.stroke(
                        Path { p in p.move(to: CGPoint(x: x, y: 0)); p.addLine(to: CGPoint(x: x, y: size.height)) },
                        with: .color(gridColor)
                    )
                    context.stroke(
                        Path { p in p.move(to: CGPoint(x: 0, y: y)); p.addLine(to: CGPoint(x: size.width, y: y)) },
                        with: .color(gridColor)
                    )
                }

                // Linear reference line (diagonal)
                context.stroke(
                    Path { p in
                        p.move(to: CGPoint(x: 0, y: size.height))
                        p.addLine(to: CGPoint(x: size.width, y: 0))
                    },
                    with: .color(Color.secondary.opacity(0.3)),
                    style: StrokeStyle(lineWidth: 1, dash: [4, 4])
                )

                // Draw curve if we have steps
                if !viewModel.builderSteps.isEmpty {
                    let sorted = viewModel.builderSteps.sorted(by: { $0.input < $1.input })
                    var path = Path()
                    for (i, step) in sorted.enumerated() {
                        let pt = CGPoint(
                            x: step.input * size.width,
                            y: size.height - step.output * size.height
                        )
                        if i == 0 { path.move(to: pt) }
                        else { path.addLine(to: pt) }
                    }
                    context.stroke(path, with: .color(.accentColor), lineWidth: 2)
                }
            }

            // Axis labels
            VStack {
                Spacer()
                HStack {
                    Text("Input Density →")
                        .font(.system(size: 10))
                        .foregroundStyle(.tertiary)
                    Spacer()
                }
            }
            .padding(8)

            HStack {
                Text("Output ↑")
                    .font(.system(size: 10))
                    .foregroundStyle(.tertiary)
                    .rotationEffect(.degrees(-90))
                Spacer()
            }
            .padding(8)
        }
        .background(Color(nsColor: .textBackgroundColor).opacity(0.5))
        .clipShape(RoundedRectangle(cornerRadius: 8))
        .overlay(
            RoundedRectangle(cornerRadius: 8)
                .strokeBorder(Color.secondary.opacity(0.2), lineWidth: 1)
        )
    }

    private var emptyBuilderState: some View {
        VStack(spacing: 12) {
            Image(systemName: "arrow.down.doc")
                .font(.system(size: 32))
                .foregroundStyle(.tertiary)
            Text("Drop a scanned target here")
                .font(.system(size: 13, weight: .medium))
                .foregroundStyle(.secondary)
            Text("Or click Load Target to browse. Supports TIFF, PNG, JPEG.")
                .font(.caption)
                .foregroundStyle(.tertiary)
                .multilineTextAlignment(.center)
                .frame(maxWidth: 300)
        }
    }
}
