import CoreGraphics
import CoreImage
import CoreML
import Foundation
import os.log

private let inpaintLog = Logger(subsystem: "HoehnPhotosOrganizer", category: "Inpainting")

// MARK: - InpaintingStrategy

/// Which inpainting model to use, based on artifact context.
enum InpaintingStrategy: String, Sendable, CaseIterable {
    /// LaMa (~200MB CoreML) — fast, excellent for dust on flat/texture backgrounds.
    /// Resolution-robust Fourier convolutions handle large masked regions well.
    case lama
    /// MAT (~400MB CoreML) — mask-aware transformer, better for hairs crossing
    /// skin/face regions where texture coherence is critical.
    case mat
    /// Auto-select: LaMa for dust, MAT for hair on faces.
    case auto
}

// MARK: - InpaintingError

enum InpaintingError: Error, LocalizedError {
    case modelNotFound(String)
    case preprocessingFailed
    case inferenceFailed(String)
    case postprocessingFailed
    case unsupportedImageSize(String)

    var errorDescription: String? {
        switch self {
        case .modelNotFound(let name):
            return "Inpainting model not found in app bundle: \(name)"
        case .preprocessingFailed:
            return "Failed to preprocess image for inpainting."
        case .inferenceFailed(let detail):
            return "Inpainting inference failed: \(detail)"
        case .postprocessingFailed:
            return "Failed to composite inpainting result."
        case .unsupportedImageSize(let detail):
            return "Image size not supported for inpainting: \(detail)"
        }
    }
}

// MARK: - InpaintingResult

struct InpaintingResult: Sendable {
    /// The final composited image with artifacts removed.
    let image: CGImage
    /// Which model was used.
    let strategy: InpaintingStrategy
    /// Number of masked pixels that were inpainted.
    let maskedPixelCount: Int
    /// Inference time in seconds.
    let inferenceTime: TimeInterval
}

// MARK: - InpaintingService

/// Runs masked inpainting using LaMa or MAT CoreML models to remove dust and
/// hair artifacts from scanned film images.
///
/// Models (added to Xcode target as .mlpackage or .mlmodelc):
///   - `LaMaInpainter.mlmodelc` — ~200MB, 512x512 input tiles
///   - `MATInpainter.mlmodelc`  — ~400MB, 512x512 input tiles
///
/// Both models accept:
///   - `image`: float32 [1, 3, 512, 512] — RGB normalised to [0, 1]
///   - `mask`:  float32 [1, 1, 512, 512] — binary mask (1 = inpaint, 0 = keep)
///
/// Output: float32 [1, 3, 512, 512] — inpainted RGB in [0, 1]
///
/// For images larger than 512x512, tiled inference is used with overlapping
/// tiles to avoid seam artifacts at tile boundaries.
actor InpaintingService {

    // MARK: - Constants

    static let lamaModelName = "LaMaInpainter"
    static let matModelName = "MATInpainter"
    private static let tileSize = 512
    private static let tileOverlap = 64  // overlap between adjacent tiles

    // MARK: - Lazy models

    private var lamaModel: MLModel?
    private var matModel: MLModel?

    /// `true` when at least one inpainting model is present in the bundle.
    nonisolated static var isAvailable: Bool {
        lamaIsAvailable || matIsAvailable
    }

    nonisolated static var lamaIsAvailable: Bool {
        Bundle.main.url(forResource: lamaModelName, withExtension: "mlmodelc") != nil
            || Bundle.main.url(forResource: lamaModelName, withExtension: "mlpackage") != nil
    }

    nonisolated static var matIsAvailable: Bool {
        Bundle.main.url(forResource: matModelName, withExtension: "mlmodelc") != nil
            || Bundle.main.url(forResource: matModelName, withExtension: "mlpackage") != nil
    }

    // MARK: - Public API

    /// Inpaint masked regions of the image, replacing dust/hair artifacts with
    /// plausible content generated by the selected model.
    ///
    /// - Parameters:
    ///   - image: Source image (any size; will be tiled internally).
    ///   - mask: Binary mask matching `image` dimensions. White (255) = inpaint.
    ///   - strategy: Which model to use (`.auto` selects based on availability).
    ///   - detections: Optional detection metadata for auto-strategy selection.
    func inpaint(
        image: CGImage,
        mask: CGImage,
        strategy: InpaintingStrategy = .auto,
        detections: [DustDetection] = []
    ) async throws -> InpaintingResult {
        let resolvedStrategy = resolveStrategy(strategy, detections: detections)
        let model = try loadModel(for: resolvedStrategy)

        let startTime = CFAbsoluteTimeGetCurrent()
        let width = image.width
        let height = image.height

        inpaintLog.info("Inpainting: \(width)x\(height) with \(resolvedStrategy.rawValue)")

        // Extract raw pixel data
        guard let imagePixels = extractRGBPixels(image),
              let maskPixels = extractGrayPixels(mask) else {
            throw InpaintingError.preprocessingFailed
        }

        // Count masked pixels for reporting
        let maskedCount = maskPixels.filter { $0 > 127 }.count

        // If no pixels need inpainting, return original
        guard maskedCount > 0 else {
            return InpaintingResult(
                image: image,
                strategy: resolvedStrategy,
                maskedPixelCount: 0,
                inferenceTime: 0
            )
        }

        // For small images that fit in a single tile, run directly
        let result: CGImage
        if width <= Self.tileSize && height <= Self.tileSize {
            result = try await inpaintSingleTile(
                imagePixels: imagePixels,
                maskPixels: maskPixels,
                width: width,
                height: height,
                model: model
            )
        } else {
            result = try await inpaintTiled(
                imagePixels: imagePixels,
                maskPixels: maskPixels,
                width: width,
                height: height,
                model: model
            )
        }

        let elapsed = CFAbsoluteTimeGetCurrent() - startTime
        inpaintLog.info("Inpainting: completed in \(String(format: "%.2f", elapsed))s, \(maskedCount) pixels inpainted")

        return InpaintingResult(
            image: result,
            strategy: resolvedStrategy,
            maskedPixelCount: maskedCount,
            inferenceTime: elapsed
        )
    }

    // MARK: - Strategy resolution

    private func resolveStrategy(
        _ strategy: InpaintingStrategy,
        detections: [DustDetection]
    ) -> InpaintingStrategy {
        switch strategy {
        case .lama, .mat:
            return strategy
        case .auto:
            // If detections include hair on faces, prefer MAT
            let hasHair = detections.contains { $0.artifactType == .hair }
            if hasHair && Self.matIsAvailable {
                return .mat
            }
            // Default to LaMa (faster, handles dust well)
            if Self.lamaIsAvailable {
                return .lama
            }
            if Self.matIsAvailable {
                return .mat
            }
            // Fallback — will fail at model load time
            return .lama
        }
    }

    // MARK: - Model loading

    private func loadModel(for strategy: InpaintingStrategy) throws -> MLModel {
        switch strategy {
        case .lama, .auto:
            return try loadLamaModel()
        case .mat:
            return try loadMATModel()
        }
    }

    private func loadLamaModel() throws -> MLModel {
        if let m = lamaModel { return m }
        let m = try loadCoreMLModel(named: Self.lamaModelName)
        lamaModel = m
        return m
    }

    private func loadMATModel() throws -> MLModel {
        if let m = matModel { return m }
        let m = try loadCoreMLModel(named: Self.matModelName)
        matModel = m
        return m
    }

    private func loadCoreMLModel(named name: String) throws -> MLModel {
        guard let url = Bundle.main.url(forResource: name, withExtension: "mlmodelc")
                     ?? Bundle.main.url(forResource: name, withExtension: "mlpackage") else {
            throw InpaintingError.modelNotFound(name)
        }
        let config = MLModelConfiguration()
        config.computeUnits = .all  // Neural Engine preferred
        let model = try MLModel(contentsOf: url, configuration: config)
        inpaintLog.info("Inpainting: Loaded \(name) from \(url.lastPathComponent)")
        return model
    }

    // MARK: - Single tile inference

    private func inpaintSingleTile(
        imagePixels: [UInt8],
        maskPixels: [UInt8],
        width: Int,
        height: Int,
        model: MLModel
    ) async throws -> CGImage {
        let tileSize = Self.tileSize

        // Prepare input tensors (pad to tileSize x tileSize if smaller)
        let imageArray = try prepareImageTensor(
            pixels: imagePixels, width: width, height: height, tileSize: tileSize
        )
        let maskArray = try prepareMaskTensor(
            pixels: maskPixels, width: width, height: height, tileSize: tileSize
        )

        // Run inference
        let inputProvider = try MLDictionaryFeatureProvider(dictionary: [
            "image": MLFeatureValue(multiArray: imageArray),
            "mask": MLFeatureValue(multiArray: maskArray)
        ])

        let output = try await model.prediction(from: inputProvider)

        // Extract output
        guard let outputArray = output.featureValue(for: "output")?.multiArrayValue
                             ?? output.featureValue(for: "var_0")?.multiArrayValue
                             ?? firstMultiArrayOutput(output) else {
            throw InpaintingError.inferenceFailed("No output tensor found")
        }

        // Composite: use inpainted pixels only where mask is white,
        // keep original pixels everywhere else
        return try compositeResult(
            original: imagePixels,
            inpainted: outputArray,
            mask: maskPixels,
            width: width,
            height: height,
            tileSize: tileSize
        )
    }

    // MARK: - Tiled inference for large images

    private func inpaintTiled(
        imagePixels: [UInt8],
        maskPixels: [UInt8],
        width: Int,
        height: Int,
        model: MLModel
    ) async throws -> CGImage {
        let tileSize = Self.tileSize
        let overlap = Self.tileOverlap
        let step = tileSize - overlap

        // Calculate tile grid
        let tilesX = max(1, Int(ceil(Double(width - overlap) / Double(step))))
        let tilesY = max(1, Int(ceil(Double(height - overlap) / Double(step))))

        inpaintLog.info("Inpainting: tiled \(tilesX)x\(tilesY) tiles (\(tileSize)px, \(overlap)px overlap)")

        // Output buffer — accumulate weighted results
        var outputR = [Float](repeating: 0, count: width * height)
        var outputG = [Float](repeating: 0, count: width * height)
        var outputB = [Float](repeating: 0, count: width * height)
        var weightMap = [Float](repeating: 0, count: width * height)

        for ty in 0..<tilesY {
            for tx in 0..<tilesX {
                let tileX = min(tx * step, max(0, width - tileSize))
                let tileY = min(ty * step, max(0, height - tileSize))
                let tileW = min(tileSize, width - tileX)
                let tileH = min(tileSize, height - tileY)

                // Check if this tile has any masked pixels
                var hasMasked = false
                for py in 0..<tileH {
                    for px in 0..<tileW {
                        let srcIdx = (tileY + py) * width + (tileX + px)
                        if maskPixels[srcIdx] > 127 { hasMasked = true; break }
                    }
                    if hasMasked { break }
                }

                // Skip tiles with no masked pixels — just copy original
                if !hasMasked {
                    for py in 0..<tileH {
                        for px in 0..<tileW {
                            let srcIdx = (tileY + py) * width + (tileX + px)
                            let rgbBase = srcIdx * 3
                            outputR[srcIdx] += Float(imagePixels[rgbBase]) / 255.0
                            outputG[srcIdx] += Float(imagePixels[rgbBase + 1]) / 255.0
                            outputB[srcIdx] += Float(imagePixels[rgbBase + 2]) / 255.0
                            weightMap[srcIdx] += 1.0
                        }
                    }
                    continue
                }

                // Extract tile pixels
                var tileImage = [UInt8](repeating: 0, count: tileSize * tileSize * 3)
                var tileMask = [UInt8](repeating: 0, count: tileSize * tileSize)

                for py in 0..<tileH {
                    for px in 0..<tileW {
                        let srcIdx = (tileY + py) * width + (tileX + px)
                        let dstIdx = py * tileSize + px
                        tileImage[dstIdx * 3] = imagePixels[srcIdx * 3]
                        tileImage[dstIdx * 3 + 1] = imagePixels[srcIdx * 3 + 1]
                        tileImage[dstIdx * 3 + 2] = imagePixels[srcIdx * 3 + 2]
                        tileMask[dstIdx] = maskPixels[srcIdx]
                    }
                }

                // Prepare tensors
                let imageArray = try prepareImageTensorFromRGB(
                    pixels: tileImage, tileSize: tileSize
                )
                let maskArray = try prepareMaskTensorDirect(
                    pixels: tileMask, tileSize: tileSize
                )

                // Run inference
                let inputProvider = try MLDictionaryFeatureProvider(dictionary: [
                    "image": MLFeatureValue(multiArray: imageArray),
                    "mask": MLFeatureValue(multiArray: maskArray)
                ])
                let output = try await model.prediction(from: inputProvider)

                guard let outputArray = output.featureValue(for: "output")?.multiArrayValue
                                     ?? output.featureValue(for: "var_0")?.multiArrayValue
                                     ?? firstMultiArrayOutput(output) else {
                    throw InpaintingError.inferenceFailed("No output tensor in tile (\(tx),\(ty))")
                }

                // Accumulate tile output with distance-based blending weight
                let outPtr = outputArray.dataPointer.bindMemory(
                    to: Float.self, capacity: 3 * tileSize * tileSize
                )
                let planeSize = tileSize * tileSize

                for py in 0..<tileH {
                    for px in 0..<tileW {
                        let tileIdx = py * tileSize + px
                        let srcIdx = (tileY + py) * width + (tileX + px)

                        // Cosine blend weight for overlap region
                        let dx = min(px, tileW - 1 - px)
                        let dy = min(py, tileH - 1 - py)
                        let edgeDist = Float(min(dx, dy))
                        let w: Float = edgeDist < Float(overlap) ?
                            0.5 * (1 + cos(Float.pi * (1 - edgeDist / Float(overlap)))) : 1.0

                        outputR[srcIdx] += outPtr[0 * planeSize + tileIdx] * w
                        outputG[srcIdx] += outPtr[1 * planeSize + tileIdx] * w
                        outputB[srcIdx] += outPtr[2 * planeSize + tileIdx] * w
                        weightMap[srcIdx] += w
                    }
                }
            }
        }

        // Normalise and composite
        var finalPixels = [UInt8](repeating: 0, count: width * height * 4)
        for i in 0..<(width * height) {
            let w = max(weightMap[i], 1e-6)
            if maskPixels[i] > 127 {
                // Inpainted region: use model output
                finalPixels[i * 4] = UInt8(clamping: Int(outputR[i] / w * 255))
                finalPixels[i * 4 + 1] = UInt8(clamping: Int(outputG[i] / w * 255))
                finalPixels[i * 4 + 2] = UInt8(clamping: Int(outputB[i] / w * 255))
            } else {
                // Preserved region: use original
                finalPixels[i * 4] = imagePixels[i * 3]
                finalPixels[i * 4 + 1] = imagePixels[i * 3 + 1]
                finalPixels[i * 4 + 2] = imagePixels[i * 3 + 2]
            }
            finalPixels[i * 4 + 3] = 255  // alpha
        }

        guard let provider = CGDataProvider(data: Data(finalPixels) as CFData),
              let result = CGImage(
                  width: width, height: height,
                  bitsPerComponent: 8, bitsPerPixel: 32, bytesPerRow: width * 4,
                  space: CGColorSpaceCreateDeviceRGB(),
                  bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.noneSkipLast.rawValue),
                  provider: provider, decode: nil,
                  shouldInterpolate: true, intent: .defaultIntent
              ) else {
            throw InpaintingError.postprocessingFailed
        }

        return result
    }

    // MARK: - Tensor preparation

    private func prepareImageTensor(
        pixels: [UInt8],
        width: Int,
        height: Int,
        tileSize: Int
    ) throws -> MLMultiArray {
        let array = try MLMultiArray(
            shape: [1, 3, tileSize as NSNumber, tileSize as NSNumber],
            dataType: .float32
        )
        let ptr = array.dataPointer.bindMemory(to: Float.self, capacity: 3 * tileSize * tileSize)
        let planeSize = tileSize * tileSize

        // Zero-fill (handles padding for images smaller than tileSize)
        memset(ptr, 0, 3 * planeSize * MemoryLayout<Float>.size)

        for y in 0..<min(height, tileSize) {
            for x in 0..<min(width, tileSize) {
                let srcIdx = (y * width + x) * 3
                let dstIdx = y * tileSize + x
                for c in 0..<3 {
                    ptr[c * planeSize + dstIdx] = Float(pixels[srcIdx + c]) / 255.0
                }
            }
        }

        return array
    }

    private func prepareImageTensorFromRGB(
        pixels: [UInt8],
        tileSize: Int
    ) throws -> MLMultiArray {
        let array = try MLMultiArray(
            shape: [1, 3, tileSize as NSNumber, tileSize as NSNumber],
            dataType: .float32
        )
        let ptr = array.dataPointer.bindMemory(to: Float.self, capacity: 3 * tileSize * tileSize)
        let planeSize = tileSize * tileSize

        for i in 0..<planeSize {
            ptr[0 * planeSize + i] = Float(pixels[i * 3]) / 255.0
            ptr[1 * planeSize + i] = Float(pixels[i * 3 + 1]) / 255.0
            ptr[2 * planeSize + i] = Float(pixels[i * 3 + 2]) / 255.0
        }

        return array
    }

    private func prepareMaskTensor(
        pixels: [UInt8],
        width: Int,
        height: Int,
        tileSize: Int
    ) throws -> MLMultiArray {
        let array = try MLMultiArray(
            shape: [1, 1, tileSize as NSNumber, tileSize as NSNumber],
            dataType: .float32
        )
        let ptr = array.dataPointer.bindMemory(to: Float.self, capacity: tileSize * tileSize)

        memset(ptr, 0, tileSize * tileSize * MemoryLayout<Float>.size)

        for y in 0..<min(height, tileSize) {
            for x in 0..<min(width, tileSize) {
                let srcIdx = y * width + x
                let dstIdx = y * tileSize + x
                ptr[dstIdx] = pixels[srcIdx] > 127 ? 1.0 : 0.0
            }
        }

        return array
    }

    private func prepareMaskTensorDirect(
        pixels: [UInt8],
        tileSize: Int
    ) throws -> MLMultiArray {
        let array = try MLMultiArray(
            shape: [1, 1, tileSize as NSNumber, tileSize as NSNumber],
            dataType: .float32
        )
        let ptr = array.dataPointer.bindMemory(to: Float.self, capacity: tileSize * tileSize)

        for i in 0..<(tileSize * tileSize) {
            ptr[i] = pixels[i] > 127 ? 1.0 : 0.0
        }

        return array
    }

    // MARK: - Composite

    private func compositeResult(
        original: [UInt8],
        inpainted: MLMultiArray,
        mask: [UInt8],
        width: Int,
        height: Int,
        tileSize: Int
    ) throws -> CGImage {
        let outPtr = inpainted.dataPointer.bindMemory(
            to: Float.self, capacity: 3 * tileSize * tileSize
        )
        let planeSize = tileSize * tileSize

        var rgba = [UInt8](repeating: 0, count: width * height * 4)

        for y in 0..<height {
            for x in 0..<width {
                let srcIdx = y * width + x
                let tileIdx = y * tileSize + x
                let dstBase = srcIdx * 4

                if mask[srcIdx] > 127, tileIdx < planeSize {
                    // Inpainted pixel
                    rgba[dstBase] = UInt8(clamping: Int(outPtr[0 * planeSize + tileIdx] * 255))
                    rgba[dstBase + 1] = UInt8(clamping: Int(outPtr[1 * planeSize + tileIdx] * 255))
                    rgba[dstBase + 2] = UInt8(clamping: Int(outPtr[2 * planeSize + tileIdx] * 255))
                } else {
                    // Original pixel
                    let rgbBase = srcIdx * 3
                    rgba[dstBase] = original[rgbBase]
                    rgba[dstBase + 1] = original[rgbBase + 1]
                    rgba[dstBase + 2] = original[rgbBase + 2]
                }
                rgba[dstBase + 3] = 255
            }
        }

        guard let provider = CGDataProvider(data: Data(rgba) as CFData),
              let result = CGImage(
                  width: width, height: height,
                  bitsPerComponent: 8, bitsPerPixel: 32, bytesPerRow: width * 4,
                  space: CGColorSpaceCreateDeviceRGB(),
                  bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.noneSkipLast.rawValue),
                  provider: provider, decode: nil,
                  shouldInterpolate: true, intent: .defaultIntent
              ) else {
            throw InpaintingError.postprocessingFailed
        }

        return result
    }

    // MARK: - Pixel extraction

    /// Extract RGB pixels (3 bytes per pixel) from a CGImage.
    private nonisolated func extractRGBPixels(_ image: CGImage) -> [UInt8]? {
        let w = image.width, h = image.height
        var data = [UInt8](repeating: 0, count: w * h * 3)

        // Draw into a 3-channel (packed RGB) context by drawing to RGBA and stripping alpha
        var rgba = [UInt8](repeating: 0, count: w * h * 4)
        guard let ctx = CGContext(
            data: &rgba, width: w, height: h,
            bitsPerComponent: 8, bytesPerRow: w * 4,
            space: CGColorSpace(name: CGColorSpace.sRGB)!,
            bitmapInfo: CGImageAlphaInfo.noneSkipLast.rawValue
        ) else { return nil }
        ctx.draw(image, in: CGRect(x: 0, y: 0, width: w, height: h))

        for i in 0..<(w * h) {
            data[i * 3] = rgba[i * 4]
            data[i * 3 + 1] = rgba[i * 4 + 1]
            data[i * 3 + 2] = rgba[i * 4 + 2]
        }
        return data
    }

    /// Extract single-channel grayscale pixels from a CGImage mask.
    private nonisolated func extractGrayPixels(_ image: CGImage) -> [UInt8]? {
        let w = image.width, h = image.height
        var data = [UInt8](repeating: 0, count: w * h)

        // If already grayscale, draw directly
        if let colorSpace = CGColorSpace(name: CGColorSpace.linearGray),
           let ctx = CGContext(
               data: &data, width: w, height: h,
               bitsPerComponent: 8, bytesPerRow: w,
               space: colorSpace,
               bitmapInfo: CGImageAlphaInfo.none.rawValue
           ) {
            ctx.draw(image, in: CGRect(x: 0, y: 0, width: w, height: h))
            return data
        }

        // Fallback: draw as RGBA and extract luminance
        var rgba = [UInt8](repeating: 0, count: w * h * 4)
        guard let ctx = CGContext(
            data: &rgba, width: w, height: h,
            bitsPerComponent: 8, bytesPerRow: w * 4,
            space: CGColorSpace(name: CGColorSpace.sRGB)!,
            bitmapInfo: CGImageAlphaInfo.noneSkipLast.rawValue
        ) else { return nil }
        ctx.draw(image, in: CGRect(x: 0, y: 0, width: w, height: h))

        for i in 0..<(w * h) {
            // Use red channel as mask intensity (mask is grayscale so R=G=B)
            data[i] = rgba[i * 4]
        }
        return data
    }

    // MARK: - Output helpers

    private func firstMultiArrayOutput(_ output: MLFeatureProvider) -> MLMultiArray? {
        for name in output.featureNames {
            if let arr = output.featureValue(for: name)?.multiArrayValue {
                return arr
            }
        }
        return nil
    }
}
